### ISSUE TITLE
Checkout button, cannot change style if class is set, and if class is set, styles overwrite class.

### ISSUE THREAD

**Issue by natecorkish** [laravel/cashier-stripe#1069] opened 2021-02-21 11:57 UTC
- Cashier Version: Latest
- Laravel Version: Latest
- PHP Version: Latest

### Description:

The `isset($style) && ! isset($class)` will not work to style buttons with classes. Because if the class isset, the if statement will return the default style, overwriting the classes. Shouldn't it be: `isset($style) && isset($class) ? $style` so the default styles don't overwrite the classes? https://raw.githubusercontent.com/laravel/cashier-stripe/a2b9716eb7b4aedb197315b61e942318441fb09e/resources/views/checkout.blade.php

I could send a PR to fix this?

```

<button
    id="checkout-{{ $sessionId }}"
    role="link"
    style="{{ isset($style) && ! isset($class) ? $style : 'background-color:#6772E5;color:#FFF;padding:8px 12px;border:0;border-radius:4px;font-size:1em' }}"
    @isset($class) class="{{ $class }}" @endisset
>
    {{ $label }}
</button>

```

The below code will still return the default style, even if I add `'style' => ''`
```
{{ $checkout->button('Pay For Job', [
    'class' => 'bg-blue-100 text-sm px-4 py-2',
]) }}
```

### Steps To Reproduce:

Please see above

**Comment by driesvints** [comment] 2021-02-22 09:02
Heya, thanks. Technically this is the way things work and not a bug so closing this. Let's focus on the open PR. 

Also: next time please fill out the version numbers.

**Closed by driesvints** 2021-02-22 09:02 UTC
